### ISSUE TITLE
High CPU temp

### ISSUE THREAD

**Issue by Dirpt** [tonuniverse/miningPoolGui#1]
Hello, when using this miner my cpu goes to 60 degrees instead of the usual 30.

did anyone have this issue also?

**Comment by Dirpt** [comment]
I'm using hiveos latest release, GPU's also are identified as CPU in the main screen. tried lolminer with ton-pool CPU does not run hot. 
<img width="1191" alt="Screenshot 2022-01-08 at 12 22 04" src="https://user-images.githubusercontent.com/97310923/148643953-d9f11967-8f5f-42ab-b02d-64761e5f588c.png">
 If there is any info i can provide and will be helpful to you please advise.

Thanks for your time.

**Comment by cryshado** [comment]
The question is not related to the GUI client
